@baseUrl = http://localhost:3001

### Get all persons
GET {{baseUrl}}/api/persons

### Get info page
GET {{baseUrl}}/info

### Get person by id
GET {{baseUrl}}/api/persons/1

### Delete person by id
DELETE {{baseUrl}}/api/persons/1

### Create person
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name": "Tai Vo",
    "number": "032-987654"
}